# Configuración de JPA y Hibernate
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configuración de la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Configuración del servidor
server:
  port: 8081
